frontend/app/build.gradle.kts, frontend/app/src/main/AndroidManifest.xml, frontend/app/src/main/java/com/example/musicroom/AuthScreens.kt, frontend/app/src/main/java/com/example/musicroom/MainActivity.kt, frontend/app/src/main/java/com/example/musicroom/UserAuthManager.kt, frontend/app/src/main/java/com/example/musicroom/api/ApiModels.kt, frontend/app/src/main/java/com/example/musicroom/api/AuthInterceptor.kt, frontend/app/src/main/java/com/example/musicroom/api/MusicRoomApi.kt, frontend/app/src/main/java/com/example/musicroom/api/RetrofitClient.kt
have added in backend integration with the phone, only the login and signup for now.
=> added backend integration

frontend-dart/lib/app.dart, frontend-dart/lib/screens/all_screens_demo.dart, frontend-dart/lib/screens/docs/api_docs_screen.dart, frontend-dart/lib/screens/home/home_screen.dart
added api docs for api to implement, may need to clean up unnnessary navbar
=> added api docs for api to implement

frontend-dart/lib/screens/home/home_screen.dart
minor code change to bottom tab
=> remove bottom tab

frontend-dart/lib/models/playlist.dart, frontend-dart/lib/models/track.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/screens/music/deezer_track_detail_screen.dart, frontend-dart/lib/screens/music/enhanced_playlist_editor_screen.dart, frontend-dart/lib/screens/music/player_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/widgets/music_player_widget.dart, frontend-dart/lib/widgets/playlist_item.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
edited track and playlist model to include in images. placeholder for now
=> attempt to add track images

frontend-dart/lib/app.dart, frontend-dart/lib/config/theme.dart, frontend-dart/lib/extensions/context_extensions.dart, frontend-dart/lib/models/track.dart, frontend-dart/lib/providers/base_provider.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/screens/music/playlist_editor_screen.dart, frontend-dart/lib/screens/music/public_playlists_screen.dart, frontend-dart/lib/widgets/error_handler.dart, frontend-dart/lib/widgets/playlist_item.dart, frontend-dart/lib/widgets/track_item.dart
another refactoring of flutter app, playlist still not fully fixed
=> another refactoring of flutter app

frontend-dart/lib/config/theme.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
card template fix, will do playlist fix later
=> minor card fix and update packages

apps/playlists/views.py
def get_user_saved_playlists(request): def get_all_shared_playlists(request): def get_playlist_info(request, playlist_id): all to return ID. 
this is my workflow, http://localhost:8000/playlists/saved_playlists from there i get the specific id then i can call http://localhost:8000/playlists/playlists/<int:playlist_id> to either get specific playlist or add tracks and etc thanks!
=> return back playlist ID as i need it in order to get specific playlist

frontend-dart/lib/core/api_constants.dart, frontend-dart/lib/core/app_strings.dart, frontend-dart/lib/core/constants.dart, frontend-dart/lib/core/core.dart, frontend-dart/lib/core/dimensions.dart, frontend-dart/lib/main.dart, frontend-dart/lib/providers/app_provider.dart, frontend-dart/lib/providers/auth_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/friends/add_friend_screen.dart, frontend-dart/lib/screens/friends/friend_request_screen.dart, frontend-dart/lib/screens/home/home_screen.dart, frontend-dart/lib/screens/music/control_delegation_screen.dart, frontend-dart/lib/screens/music/deezer_track_detail_screen.dart, frontend-dart/lib/screens/music/playlist_editor_screen.dart, frontend-dart/lib/screens/music/playlist_sharing_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/playlists/playlists_screen.dart, frontend-dart/lib/screens/playlists/public_playlists_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/utils/dialog_utils.dart, frontend-dart/lib/utils/snackbar_utils.dart, frontend-dart/lib/utils/utils.dart, frontend-dart/lib/utils/validation.dart, frontend-dart/lib/widgets/music_player_widget.dart
added quite a lot of constants then have to edit so many files
=> added more constant values, edited quite a few scripts

frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/friends/add_friend_screen.dart, frontend-dart/lib/screens/friends/friends_screen.dart, frontend-dart/lib/screens/home/home_screen.dart, frontend-dart/lib/screens/music/playlist_editor_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/profile/profile_screen.dart, frontend-dart/lib/widgets/api_error_widget.dart, frontend-dart/lib/widgets/common_widgets.dart, frontend-dart/lib/widgets/music_player_widget.dart
updating UI to be more verbose, ok maybe too verbose.
=> updating UI to be more verbose

frontend-dart/Dockerfile, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
no more root, but dockerfile gets longer, need to wait 5 minutes to build.
=> no more root, but dockerfile gets longer

frontend-dart/lib/app.dart, frontend-dart/lib/core/app_builder.dart, frontend-dart/lib/core/consolidated_core.dart, frontend-dart/lib/core/service_locator.dart, frontend-dart/lib/core/ui_helpers.dart, frontend-dart/lib/main.dart, frontend-dart/lib/models/api_models.dart, frontend-dart/lib/models/collaboration_models.dart, frontend-dart/lib/models/models.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/base_screen.dart, frontend-dart/lib/screens/home/home_screen.dart, frontend-dart/lib/screens/music/control_delegation_screen.dart, frontend-dart/lib/screens/music/music_features_screen.dart, frontend-dart/lib/screens/music/track_detail_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/music/track_selection_screen.dart, frontend-dart/lib/screens/music/track_vote_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/playlists/playlist_editor_screen.dart, frontend-dart/lib/widgets/app_cards.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/lib/widgets/common_widgets.dart, frontend-dart/lib/widgets/network_connectivity_widget.dart, frontend-dart/lib/widgets/unified_components.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
track add button is there, but need workaround to add local tracks first
=> track add button is there, but need workaround

apps/playlists/views.py
added deezerid to returned tracks so that it is easier for me to use deezer sdk from the ID
=> added deezerid to returned tracks

frontend-dart/lib/core/app_builder.dart, frontend-dart/lib/core/base_provider.dart, frontend-dart/lib/core/core.dart, frontend-dart/lib/core/service_locator.dart, frontend-dart/lib/models/api_models.dart, frontend-dart/lib/models/models.dart, frontend-dart/lib/models/sort_models.dart, frontend-dart/lib/models/voting_models.dart, frontend-dart/lib/providers/auth_provider.dart, frontend-dart/lib/providers/device_provider.dart, frontend-dart/lib/providers/friend_provider.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/providers/voting_provider.dart, frontend-dart/lib/screens/music/track_detail_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/profile/social_network_link_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/voting_service.dart, frontend-dart/lib/services/websocket_service.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/lib/widgets/voting_widgets.dart
voting half implemented, didnt display on UI cause of device permission.
=> voting half implemented

frontend-dart/lib/models/models.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/auth_service.dart, frontend-dart/lib/services/music_service.dart, frontend-dart/lib/services/storage_service.dart
fixed persistent login issue and attempted to set timeout for tracks.
=> fixed persistent login issue

frontend-dart/android/app/src/main/AndroidManifest.xml, frontend-dart/lib/core/core.dart, frontend-dart/lib/core/service_locator.dart, frontend-dart/lib/main.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/providers/voting_provider.dart, frontend-dart/lib/screens/music/track_detail_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/playlists/playlist_licensing_screen.dart, frontend-dart/lib/screens/profile/profile_screen.dart, frontend-dart/lib/screens/profile/social_network_link_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/music_service.dart, frontend-dart/lib/widgets/voting_widgets.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
added permissions on android manifest too.
=> partial implementation of avatar upload and fix print

frontend-dart/lib/core/core.dart, frontend-dart/lib/main.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/auth/signup_with_otp_screen.dart, frontend-dart/lib/screens/friends/add_friend_screen.dart, frontend-dart/lib/screens/music/track_detail_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/playlists/playlist_editor_screen.dart, frontend-dart/lib/screens/playlists/playlist_licensing_screen.dart, frontend-dart/lib/screens/profile/profile_screen.dart, frontend-dart/lib/screens/profile/social_network_link_screen.dart, frontend-dart/lib/screens/profile/user_password_change_screen.dart, frontend-dart/lib/services/track_sorting_service.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
think time to add back song bar?
=> finally fix the vote count state, need fix the floating add song button

frontend-dart/android/app/build.gradle.kts, frontend-dart/android/build.gradle.kts, frontend-dart/lib/core/core.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/providers/voting_provider.dart, frontend-dart/lib/screens/base_screen.dart, frontend-dart/lib/screens/home/home_screen.dart, frontend-dart/lib/screens/music/track_detail_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/playlists/playlist_editor_screen.dart, frontend-dart/lib/services/track_sorting_service.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/lib/widgets/voting_widgets.dart
fixed voting system, removed downvote icon.
=> constant update to the playlist when track position changed

frontend-dart/lib/core/core.dart, frontend-dart/lib/core/theme_utils.dart, frontend-dart/lib/providers/friend_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/friends/add_friend_screen.dart, frontend-dart/lib/screens/friends/friend_request_screen.dart, frontend-dart/lib/screens/friends/friends_list_screen.dart, frontend-dart/lib/screens/home/home_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_widgets.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/friend_service.dart
=> properly added friend implementation, remove some minor utils

frontend-dart/lib/models/api_models.dart, frontend-dart/lib/models/models.dart, frontend-dart/lib/providers/auth_provider.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/auth_service.dart, frontend-dart/lib/services/music_service.dart
added profile and service for api, haven edit widget page yet.
=> partial implementation for profile api

apps/remote_auth/views.py, frontend-dart/lib/models/api_models.dart, frontend-dart/lib/providers/auth_provider.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/profile/profile_screen.dart, frontend-dart/lib/screens/profile/social_network_link_screen.dart, frontend-dart/lib/services/auth_service.dart
Backend:
Modify apps/remote_auth/views.py.
1) To allow google login (web) using 'email', 'username', 'social id' , in addition to using idToken from Android app google login.
2) Allow social network - google linking to follow as above.
Frontend:
Modify 
frontend-dart/lib/models/api_models.dart
frontend-dart/lib/providers/auth_provider.dart
frontend-dart/lib/providers/profile_provider.dart
frontend-dart/lib/screens/auth/auth_screen.dart
frontend-dart/lib/screens/profile/profile_screen.dart
frontend-dart/lib/screens/profile/social_network_link_screen.dart
frontend-dart/lib/services/auth_service.dart
To allow google login (web), social network linking.
=> Fix web google login + social network linking

core/settings.py, docker/requirements.txt
Backend:
Add drf_api_logger to log API request.
Please see if this package can meet the logging requirement.
See the log at: http://localhost:8000/admin/
admin login: admin, admin
=> Add drf_api_logger

frontend-dart/lib/core/theme_utils.dart, frontend-dart/lib/main.dart, frontend-dart/lib/screens/admin/admin_dashboard_screen.dart, frontend-dart/lib/screens/admin/admin_webview_screen.dart, frontend-dart/lib/screens/profile/user_password_change_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
added feature to visit other sites, some attempt to edit theme.
=> added feature to visit other sites

frontend-dart/lib/main.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
removed the old flutter web library gets replaced.
=> quick fix on mobile pubspec error

apps/users/docs.py, apps/users/docs_serializers.py, apps/users/tests/test_check_email.py, apps/users/views.py
Back-end
/users/check_email/
Modify check_email to check email is in Social network table as well.
Add swagger and pytest.
=> Modify check_email, add swagger and pytest

frontend-dart/lib/core/app_builder.dart, frontend-dart/lib/core/theme_utils.dart, frontend-dart/lib/models/api_models.dart, frontend-dart/lib/providers/friend_provider.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/screens/friends/add_friend_screen.dart, frontend-dart/lib/screens/friends/friend_request_screen.dart, frontend-dart/lib/screens/friends/friends_list_screen.dart, frontend-dart/lib/screens/home/home_screen.dart, frontend-dart/lib/screens/playlists/playlist_licensing_screen.dart, frontend-dart/lib/screens/playlists/playlist_sharing_screen.dart, frontend-dart/lib/screens/profile/user_page_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/friend_service.dart, frontend-dart/lib/services/music_service.dart, frontend-dart/test/models/api_models_test.dart, frontend-dart/test/providers/friend_provider_test.dart, frontend-dart/test/services/music_service_test.dart
friend id now accept uuid-strings no more int validation error
=> friend id now accept uuid-strings

frontend-dart/android/app/src/main/AndroidManifest.xml, frontend-dart/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, frontend-dart/android/gradle.properties, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/music/track_search_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/widgets/app_widgets.dart
fixed ui and webview, that one is edit android permissions.
=> fixed ui and webview

frontend-dart/lib/core/theme_utils.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/track_sorting_service.dart
minor code cleanup, just remove unused functions
=> minor code cleanup

frontend-dart/lib/core/logging_navigation_observer.dart, frontend-dart/lib/core/theme_utils.dart, frontend-dart/lib/models/api_models.dart, frontend-dart/lib/providers/friend_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/profile/profile_screen.dart, frontend-dart/lib/services/frontend_logging_service.dart, frontend-dart/lib/services/music_player_service.dart, frontend-dart/lib/services/websocket_service.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/lib/widgets/custom_scrollbar.dart, frontend-dart/lib/widgets/playlist_voting_widgets.dart, frontend-dart/test/services/frontend_logging_service_sanitization_integration_test.dart, frontend-dart/test/services/frontend_logging_service_test.dart, frontend-dart/test/services/music_player_service_test.dart
fixed friend request issue by editing the right key
=> fixed friend request issue

apps/playlists/views.py, frontend-dart/lib/core/base_provider.dart, frontend-dart/lib/core/constants.dart, frontend-dart/lib/core/responsive_utils.dart, frontend-dart/lib/core/social_login.dart, frontend-dart/lib/core/theme_utils.dart, frontend-dart/lib/models/music_models.dart, frontend-dart/lib/providers/music_provider.dart, frontend-dart/lib/providers/profile_provider.dart, frontend-dart/lib/providers/voting_provider.dart, frontend-dart/lib/screens/auth/auth_screen.dart, frontend-dart/lib/screens/auth/forgot_password_screen.dart, frontend-dart/lib/screens/playlists/playlist_detail_screen.dart, frontend-dart/lib/screens/playlists/playlists_screen.dart, frontend-dart/lib/screens/profile/profile_screen.dart, frontend-dart/lib/services/api_service.dart, frontend-dart/lib/services/music_player_service.dart, frontend-dart/lib/widgets/form_widgets.dart, frontend-dart/lib/widgets/playlist_detail_widgets.dart, frontend-dart/lib/widgets/voting_widgets.dart, frontend-dart/test/core/responsive_utils_test.dart, frontend-dart/test/core/social_login_test.dart, frontend-dart/test/screens/profile/widgets/music_preference_dialog_test.dart, frontend-dart/test/widgets/dialog_widgets_test.dart
fixed deleting by actually editing get playlist api
=> fixed deleting

frontend-dart/lib/core/builder_core.dart, frontend-dart/lib/providers/theme_providers.dart, frontend-dart/lib/screens/home/home_screens.dart, frontend-dart/lib/services/logging_services.dart, frontend-dart/lib/widgets/app_widgets.dart
=> fixed the friend notification issue

apps/profile/docs.py, apps/profile/views.py, profile_curls.txt
=> GET profile/me

frontend-dart/lib/screens/friends/list_friends.dart, frontend-dart/lib/screens/profile/user_profile.dart, frontend-dart/lib/services/cache_services.dart, frontend-dart/lib/widgets/detail_widgets.dart
vote count no longer zero on top
=> fixed the vote count

frontend-dart/lib/core/animations_core.dart, frontend-dart/lib/core/constants_core.dart, frontend-dart/lib/core/theme_core.dart, frontend-dart/lib/providers/beacon_providers.dart, frontend-dart/lib/providers/music_providers.dart, frontend-dart/lib/providers/profile_providers.dart, frontend-dart/lib/screens/base_screens.dart, frontend-dart/lib/screens/home/home_screens.dart, frontend-dart/lib/services/api_services.dart, frontend-dart/lib/services/player_services.dart, frontend-dart/lib/widgets/detail_widgets.dart, frontend-dart/lib/widgets/location_widgets.dart, frontend-dart/lib/widgets/sort_widgets.dart, frontend-dart/lib/widgets/state_widgets.dart, frontend-dart/lib/widgets/votes_widgets.dart, frontend-dart/test/services/track_cache_service_test.dart
and fix some flutter analyze issues.
=> fixed the profile issue

frontend-dart/lib/core/social_core.dart, frontend-dart/lib/models/api_models.dart, frontend-dart/lib/models/music_models.dart, frontend-dart/lib/providers/music_providers.dart, frontend-dart/lib/screens/playlists/detail_playlists.dart, frontend-dart/lib/screens/playlists/editor_playlists.dart, frontend-dart/lib/services/api_services.dart, frontend-dart/lib/services/notification_services.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/lib/widgets/avatar_widgets.dart, frontend-dart/lib/widgets/dialog_widgets.dart
also fixed edit playlist name and description
=> removed playlist access control menu, redundant

frontend-dart/lib/core/logging_core.dart, frontend-dart/lib/screens/auth/signup_auth.dart, frontend-dart/lib/screens/home/home_screens.dart, frontend-dart/lib/widgets/votes_widgets.dart, frontend-dart/test/core/logging_core_test.dart
the voting settings is collapsed so that user knows they can vote first.
=> added clearer instructions on voting

frontend-dart/README.md
just indicating the files for this project
=> edited frontend readme

apps/playlists/views.py, frontend-dart/lib/core/social_core.dart, frontend-dart/lib/models/music_models.dart, frontend-dart/lib/providers/auth_providers.dart, frontend-dart/lib/screens/auth/auth_screens.dart, frontend-dart/lib/screens/playlists/sharing_playlists.dart, frontend-dart/test/models/music_models_test.dart, frontend-dart/test/screens/admin/admin_webview_screen_test.dart, frontend-dart/test/screens/playlists/playlists_screen_test.dart, frontend-dart/test/services/track_sorting_service_test.dart
=> removed useless sharing of links

frontend-dart/android/app/build.gradle.kts, frontend-dart/android/build.gradle.kts, frontend-dart/lib/core/builder_core.dart, frontend-dart/lib/core/constants_core.dart, frontend-dart/lib/core/social_core.dart, frontend-dart/lib/main.dart, frontend-dart/lib/providers/animation_providers.dart, frontend-dart/lib/providers/auth_providers.dart, frontend-dart/lib/providers/profile_providers.dart, frontend-dart/lib/providers/voting_providers.dart, frontend-dart/lib/screens/music/detail_music.dart, frontend-dart/lib/screens/music/search_music.dart, frontend-dart/lib/screens/playlists/detail_playlists.dart, frontend-dart/lib/services/api_services.dart, frontend-dart/lib/services/cache_services.dart, frontend-dart/lib/widgets/app_widgets.dart, frontend-dart/lib/widgets/detail_widgets.dart, frontend-dart/lib/widgets/dialog_widgets.dart, frontend-dart/lib/widgets/location_widgets.dart, frontend-dart/lib/widgets/votes_widgets.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml, frontend-dart/test/services/track_cache_service_test.dart
now voting message error uses backend, only left voting setting to save
=> now voting message error uses backend

frontend-dart/lib/screens/music/detail_music.dart, frontend-dart/lib/screens/music/search_music.dart, frontend-dart/lib/screens/playlists/main_playlists.dart, frontend-dart/lib/services/auth_services.dart, frontend-dart/lib/services/cache_services.dart, frontend-dart/lib/services/websocket_services.dart
erm add track to playlist will show events too.
=> now non event will not show vote at all, not yet tried to toggle

frontend-dart/lib/services/cache_services.dart, frontend-dart/lib/widgets/dialog_widgets.dart, frontend-dart/lib/widgets/sections_widgets.dart, frontend-dart/test/core/animations_core_test.dart, frontend-dart/test/widgets/player_widgets_test.dart
=> fixed music preference window

frontend-dart/lib/core/signin_core.dart, frontend-dart/lib/main.dart, frontend-dart/lib/providers/auth_providers.dart, frontend-dart/lib/providers/profile_providers.dart, frontend-dart/lib/screens/admin/dashboard_admin.dart, frontend-dart/lib/screens/auth/signup_auth.dart, frontend-dart/lib/screens/friends/list_friends.dart, frontend-dart/lib/services/location_services.dart, frontend-dart/lib/widgets/action_widgets.dart, frontend-dart/pubspec.lock, frontend-dart/pubspec.yaml
=> revert to version 6, security not worth it

core/settings.py, frontend-dart/lib/screens/playlists/detail_playlists.dart, frontend-dart/lib/screens/playlists/main_playlists.dart, frontend-dart/lib/services/api_services.dart, frontend-dart/lib/services/cache_services.dart, frontend-dart/lib/services/playlists_services.dart, frontend-dart/lib/widgets/avatar_widgets.dart, frontend-dart/lib/widgets/sort_widgets.dart
partial edit to vote settings, fixed the unwanted error message for non owner playlists.
=> Frontend throttle

frontend-dart/lib/models/sort_models.dart, frontend-dart/lib/providers/voting_providers.dart, frontend-dart/lib/screens/playlists/detail_playlists.dart, frontend-dart/lib/screens/playlists/editor_playlists.dart, frontend-dart/lib/widgets/core_widgets.dart, frontend-dart/lib/widgets/sort_widgets.dart
added sorting by most likes by default.
=> now sorted by most likes

frontend-dart/lib/screens/music/search_music.dart, frontend-dart/lib/screens/playlists/collaborative_playlists.dart, frontend-dart/lib/screens/playlists/detail_playlists.dart
voted tracks will remain there forever.
=> block deletion of voted tracks

frontend-dart/lib/screens/friends/add_friends.dart, frontend-dart/lib/screens/music/search_music.dart, frontend-dart/lib/screens/playlists/collaborative_playlists.dart, frontend-dart/lib/screens/playlists/detail_playlists.dart, frontend-dart/lib/screens/playlists/editor_playlists.dart, frontend-dart/lib/screens/profile/user_profile.dart, frontend-dart/lib/services/playlists_services.dart, frontend-dart/lib/widgets/form_widgets.dart, frontend-dart/lib/widgets/location_widgets.dart, frontend-dart/lib/widgets/votes_widgets.dart
=> Frontend event

frontend-dart/lib/screens/playlists/detail_playlists.dart, frontend-dart/test/core/locator_core_test.dart, frontend-dart/test/core/theme_core_test.dart, frontend-dart/test/models/sort_models_test.dart
=> disable sharing for non-owner
